#!/usr/bin/env bash
set -euo pipefail

readonly PACKAGE_NAME='lapki-compiler'
readonly PROJECT_ROOT='/src'
readonly DIST_DIR="$PROJECT_ROOT/dist"
readonly PACKAGE_ROOT="$PROJECT_ROOT/build/debian-root"

version="$(python3.10 - <<'PY'
import re

with open('/src/pyproject.toml', encoding='utf-8') as file:
    content = file.read()

match = re.search(
    r'^\s*version\s*=\s*["\']([^"\']+)["\']\s*$',
    content,
    flags=re.MULTILINE,
)
if match is None:
    raise SystemExit('Unable to read [tool.poetry].version from pyproject.toml')
print(match.group(1))
PY
)"
architecture="$(dpkg --print-architecture)"

rm -rf "$PACKAGE_ROOT"
mkdir -p "$DIST_DIR" \
         "$PACKAGE_ROOT/DEBIAN" \
         "$PACKAGE_ROOT/usr/lib/$PACKAGE_NAME" \
         "$PACKAGE_ROOT/usr/bin"

# Keep PyInstaller's conventional build/, dist/ and project-root .spec paths.
# The .spec file is generated by PyInstaller on every run and removed below.
cd "$PROJECT_ROOT"
pyinstaller --clean --noconfirm --onefile --name "$PACKAGE_NAME" \
    compiler/__main__.py
rm -f "$PROJECT_ROOT/$PACKAGE_NAME.spec"

install -m 0755 "$DIST_DIR/$PACKAGE_NAME" \
    "$PACKAGE_ROOT/usr/lib/$PACKAGE_NAME/$PACKAGE_NAME"
for resource in platforms library ACCESS_TOKENS.txt; do
    if [[ -e "$PROJECT_ROOT/compiler/$resource" ]]; then
        cp -a "$PROJECT_ROOT/compiler/$resource" \
            "$PACKAGE_ROOT/usr/lib/$PACKAGE_NAME/"
    fi
done
mkdir -p "$PACKAGE_ROOT/usr/lib/$PACKAGE_NAME/fullgraphmlparser"
cp -a "$PROJECT_ROOT/compiler/fullgraphmlparser/templates" \
    "$PACKAGE_ROOT/usr/lib/$PACKAGE_NAME/fullgraphmlparser/"

cat > "$PACKAGE_ROOT/usr/bin/$PACKAGE_NAME" <<'LAUNCHER'
#!/bin/sh
set -eu
app_dir=/usr/lib/lapki-compiler
state_dir="${XDG_STATE_HOME:-$HOME/.local/state}/lapki-compiler"
mkdir -p "$state_dir/build"
exec "$app_dir/lapki-compiler" \
    --library-path "$app_dir/library" \
    --platform-directory "$app_dir/platforms" \
    --access-token-path "$app_dir/ACCESS_TOKENS.txt" \
    --build-path "$state_dir/build" \
    "$@"
LAUNCHER
chmod 0755 "$PACKAGE_ROOT/usr/bin/$PACKAGE_NAME"

cat > "$PACKAGE_ROOT/DEBIAN/control" <<CONTROL
Package: $PACKAGE_NAME
Version: $version
Section: devel
Priority: optional
Architecture: $architecture
Maintainer: Lapki project
Description: Lapki compiler service
 Frozen Lapki compiler with platform definitions and source libraries.
 Depends: libc6 (>= 2.35), gcc-arm-none-eabi, make
 Recommends: arduino-cli
CONTROL

dpkg-deb --build --root-owner-group "$PACKAGE_ROOT" \
    "$DIST_DIR/${PACKAGE_NAME}_${version}_${architecture}.deb"
printf 'Created %s\n' "$DIST_DIR/${PACKAGE_NAME}_${version}_${architecture}.deb"
